#####################################################
# Select the physics
# Must be before /run/initialize
#

/DetSys/phys/SelectPhysics QGSP_BIC
/DetSys/phys/SelectPhysics standardNR # from TestEm7, w/ G4ScreenedNuclearRecoil
#/DetSys/phys/SelectPhysics standardSS # from TestEm7, single scattering

#####################################################
# Initialize the run
#

/run/initialize
/control/execute vis.mac
/tracking/verbose 0

######################################################
# Geometry
#

## the world
#
#/DetSys/world/material Vacuum

## vacuum chamber
#
/DetSys/app/setTISTARVacuumChamberShape box
/DetSys/app/setTISTARVacuumChamberMaterial Vacuum
/DetSys/app/setTISTARVacuumChamberBoxDimensions 15 15 20 cm
/DetSys/app/setTISTARVacuumChamberCylinderRadius 8 cm
/DetSys/app/setTISTARVacuumChamberCylinderZ 20 cm
/DetSys/app/setTISTARVacuumChamberExteriorMaterial G4_Al
/DetSys/app/setTISTARVacuumChamberExteriorThickness 1 mm
/DetSys/app/addTISTARVacuumChamber

## first layer
#
/DetSys/det/setTISTARDetectorNumber 10
/DetSys/det/setTISTARSiDimensions 40 0.02 50 mm  
/DetSys/det/setTISTARPCBDimensions 80 1.67 75 mm
/DetSys/det/setTISTARSiOffsetInPCB 5 0 0 mm         
/DetSys/det/setTISTARDistFromBeam 10 mm
/DetSys/det/setTISTARGapZ 4 mm
# for shifting the inner layer so that it lines up with the outer layers
# y shift = (inner layer dist from beam) * (y-shift of the outer layer) / (outer [second] layer dist from beam)
# fPositionOffset = G4ThreeVector(0., 10.0*mm*(-5.0*mm -100.0/2.*mm +140.0/2.*mm)/(30.0*mm), 0.); 
/DetSys/det/setTISTARPositionOffset 0 5 0 mm
/DetSys/det/addTISTAR4StripLayer

## second layer
#
/DetSys/det/setTISTARDetectorNumber 20
/DetSys/det/setTISTARSiDimensions 100 0.150 100 mm  
/DetSys/det/setTISTARPCBDimensions 140 1.67 140 mm
/DetSys/det/setTISTARSiOffsetInPCB 5 0 0 mm         
/DetSys/det/setTISTARSiCentered 0
/DetSys/det/setTISTARDistFromBeam 30 mm
/DetSys/det/addTISTAR2StripLayer

## third layer
#
/DetSys/det/setTISTARDetectorNumber 30
/DetSys/det/setTISTARSiDimensions 100 2 100 mm  
/DetSys/det/setTISTARPCBDimensions 140 1.67 140 mm
/DetSys/det/setTISTARSiOffsetInPCB 5 0 0 mm         
/DetSys/det/setTISTARSiCentered 0
/DetSys/det/setTISTARDistFromBeam 33 mm
/DetSys/det/addTISTAR2StripLayer

## target
#
/DetSys/miniball/SetTargetMaterialName 2H
/DetSys/miniball/SetTargetDiameter 10.0 mm
/DetSys/miniball/SetTargetThickness 2.582e-1        # in mg/cm2 (50: 1.292e-1 , 100:2.582e-1)
/DetSys/miniball/SetTargetMaterialDensity 1.614e-5  # in g/cm3 (50: 8.072e-6 , 100:1.614e-5)
/DetSys/miniball/SetGasTargetLength 16.0 cm
/DetSys/miniball/SetTargetPressure 0.100 bar
/DetSys/miniball/SetTargetMylarThickness 2 um
/DetSys/miniball/SetTargetBeWindowThickness 8 um
/DetSys/app/addTISTARGasTarget

## GRIFFIN
#
#/DetSys/det/addGriffinBackDetector 1
#/DetSys/det/addGriffinBackDetector 2
#/DetSys/det/addGriffinBackDetector 3
#/DetSys/det/addGriffinBackDetector 4
#/DetSys/det/addGriffinBackDetector 5
#/DetSys/det/addGriffinBackDetector 6
#/DetSys/det/addGriffinBackDetector 7
#/DetSys/det/addGriffinBackDetector 8
#/DetSys/det/addGriffinBackDetector 9
#/DetSys/det/addGriffinBackDetector 10
#/DetSys/det/addGriffinBackDetector 11
#/DetSys/det/addGriffinBackDetector 12
#/DetSys/det/addGriffinBackDetector 13
#/DetSys/det/addGriffinBackDetector 14
#/DetSys/det/addGriffinBackDetector 15
#/DetSys/det/addGriffinBackDetector 16

## GRIFFIN structure
#
#/DetSys/app/addGriffinStructure 0

#####################################################
# TRex/Miniball generator commands
#

/DetSys/miniball/SetPrimaryGenerator                AngularDistribution
/DetSys/miniball/SetLevelFile                       ../Data/LevelFiles/132Sn_dp.dat
/DetSys/miniball/SetAngularDistributionFile         ../Data/AngularDistributionFiles/132Sn_dp.dat
/DetSys/miniball/SetMassFile                        ../Data/MassFile.dat
/DetSys/miniball/SetReactionZvsRadiusFile           ../Data/ReactionZvsRadiusFile.dat
/DetSys/miniball/SetReactionZDistributionFile       ../Data/ReactionZDistributionFile.dat

/DetSys/miniball/SetBeamEnergy 792.0 MeV
/DetSys/miniball/SetBeamWidth 1.0 mm

/DetSys/miniball/SetProjectileName 132Sn
/DetSys/miniball/SetProjectileZ 50
/DetSys/miniball/SetProjectileA 132

/DetSys/miniball/SetTargetName 2H
/DetSys/miniball/SetTargetZ 1
/DetSys/miniball/SetTargetA 2

/DetSys/miniball/SetEjectileName 133Sn
/DetSys/miniball/SetEjectileZ 50
/DetSys/miniball/SetEjectileA 133

/DetSys/miniball/SetRecoilName 1H
/DetSys/miniball/SetRecoilZ 1
/DetSys/miniball/SetRecoilA 1

/DetSys/miniball/SetTransferOrCoulexProbability 1.0

/DetSys/miniball/SimulateGammas false
/DetSys/miniball/IncludeEnergyResolution 1
/DetSys/miniball/SimulateEjectiles false

/DetSys/miniball/Print

/DetSys/gun/useTRexGenerator false

#####################################################
# GPS commands
#

/gps/particle proton
#/gps/particle ion
#/gps/ion 50 132 0 0 

/gps/position 0 0 -100 mm
/gps/pos/type Plane
/gps/pos/shape Circle
/gps/pos/radius 1 mm
/gps/direction 0 0 1 

/gps/energy 792 MeV

/DetSys/gun/useGPS true

#####################################################
# Start the run
#

/run/beamOn 1

